/* Generated by Tessent Shell 2014.4 at Tue May 19 11:02:44 2015 */
module PLL(CTRL, RESET, LOCK, VCO, VCO_X, FB, REF);
  input  [7:0] CTRL;
  input  RESET, FB, REF;
  output LOCK, VCO, VCO_X;

endmodule
